#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 97e9fbfe-a062-483f-81b0-9e64f0ac0128
# Source File: ..\Users\preston_zc\Documents\SAPIEN\PowerShell Studio\Projects\Password-Reset\Password-Reset.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
YwIAAB+LCAAAAAAABACtkk9vwiAchu8mfoemdyztjLNJ5bCYLh62mdbsamj7Y7IhNEA1fvux0RqN
W3bZjQdenjf8yQqo1QH0aUktJeNREGRrrd6htt/g8BW04UqSZIKzaIB+LecCVkuS3kPKKgaI4lmC
pvM7huZxhVEKsynDtMZxMs+iPtxv7Vs2pxaIE1/iIFeicXVBdNlmeugxeOi4aBYhDklpqbZdO2mN
8V2/JYMCGGiQNeSdrK07ziIsd+qIniiXudL7bWtYSAZyQvaHsNxRDW640R38qF/Jg/oA9ChURYXT
xyHxY+Ps8T/Z19SYo9LNtgAD1rdcz92UefB3en4DTy+av3FJxVfgme7hrEKDqnXxLLrJjUdZdPWp
PgHkS0nHYwIAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.141
     Generated on:       7/17/2017 5:39 AM
     Generated by:       Preston_ZC
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2gMAAB+LCAAAAAAABAC9k0tLAzEQgO+C/yH0vGR33a5rIbsglV4EFVfUazadLcE8yiRpyb+3rVJF
QaGHMJd5MPMxL/YIwm4A4w33nOwUJ61pJxe0nHTnZ4Swe5QrabhaSAV3XEPXe44+rOnaOZb/ih5y
rp0DPSgJ7mB/eWKnnbCo5JCR50/WlBZ7ycg8KB8QWgPBI1cZeQi7GuIW4pN9A9MOTcNrUV+Ws2oK
xdWM5ceqPyl9dB50CgZ9kWZpt44uLGqXhLjfVBoQ8q00q1NYRTXWYzOW5bIueMX/Z71qlaSnuUVI
MzyJILzF2ANupICTbuPvMR7Nj0dj+fdf7t4BtbYVHtoDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
EmsAAB+LCAAAAAAABADtnV9zojoUwN+d8TswvuoU/1adsc6gtrvdbXd17d5796mDGCktJh2gWvvp
7yFIiwokoGuhJTvjempCkl/OOckJETu/kEIWyFgNZEsW4I2pEXxWqJ5UCt18ThA6Pw1N1bCsX2g6
+iHPUfda1vAFMeYnj+asI+587BSa3CPFEqzVIzorjFemheYn/2p4SpbmiV3WeS0Jfh+VhH/Wraif
lO1/JaH/pFtPBjrD6MkyZL0kDJ8muqZ8R6sb8oDw2aTZlBtK47TSrtVRudUuCBiaclZwm1oQlDtN
nxqQtdAn2DKIbjrdg7YODfKIDGu1LiM9WWSsyDq6JlNU6P4gGHVEN09YGe0Fst8YT/zZnRq+GGQp
4en4ztDwA7NsX9cQtpzKqu1qSag12sxClwrBbn/h0x4MmLHqSpLUk6RzaXQO7+D/S0kiI3h3ocJL
X3U+hqRKr58Hpnzu7f1AtF/FJbwMW7Fk52r7XMEr21fbv02uDFc7QJtcOZ87VC8zbhm3jFvGLeOW
ccu4Zdwybhm3jFtKuamX/c/KDbouiZCgpwdMm1crDu/r4mlfJR+IG6e+1fuSOozLLWqiY/kxuHHJ
RUm9HByA23YKu1pb/fMl7dx4/ZvrGw7BjS+9tMSh+CyNzlPNjUv2eIZjaK+XbKq5HcO/UU7FpXk1
YNJeNIuiH9dPyY1VgnISR+UfwVzftBc3irOMG5e8ktR87pJB1k339eIw4+bKDDt9kZbXQKs1ZHP9
86Wn7sfteiAtvb4kxdxYcrknjTxcA2dA6l5tsvvp2+i8ByuZAdRXVMn3FHNj22m1p/5hRxyUK9W3
vexU+dpb7lybrmxSx40l13pLJYDrhvbOau1dstH1jXzvq2ED+PuiN0oFN7ad0p0BpsYOYQUrghkH
9pqpb+AEBiLMkCNmXa0BXG2ZdG4hOSgnTq75HIssQ15eDwYieHLqCRixDLidheiMRBK5cXFtD0bl
ITtqK85wQ9zLvzl7DS7Z0ARrunsxudy8sr+deslG4RrHvxVHD9/813M+Y0rn0+RyY8l0JqIrH2ZP
Y+xtefQtQsxMnQBdWSeXW5D8pm9BZKNw5bBTiO14IzvqyWPt8iRp3UtX+8yeiqBDTdGZe2K1yROB
sPff6F4EJ9ekrnvX8SkrReAaYKd8EQhNk2p7kXRuthxup6y1Ok1gmS/rlU9M/xawntsZUxrb8cYH
78mNJW9zDdBeD9koNTj6xr/uCI/sksRtW97QN/4oCHwe9uHKZ6eUU3Gg1hlc7TGlLmefCOQY3Fgl
mFw92uuQjdUmZ3YcLPM59rqDPwJJcLwAPbXnovrPAdvHwmwyYXANtlP+u51v67kEc2Pb6UbcHs7V
XjnEiIKoTfjNjj6efI/1XLLihc2oPXjFRaMgugqN4d/oiSW+vSw6O/qecEoWN7adOmRZyS+65LZT
LptYj2nA/Jg8biyZdz+ERpc0Ho1nE5znHGCZNeOYHd+fG9tOnbtNrMSK2sPslK8GahPrnaw0cAsp
4ZwhAPPm2Q8xTouLyPshATX4ay9V1pC9rMRw4+s13Wfi3A+J7t+cu+kqrOWYYxdkE4njxrZTjlMv
bqIhZnT/VumNfjNOKXzsczXePUN/7Y16hoDKtR5EH0F3fePUkDRuXpmlb2+nbdcpdJ8p2E4j3Juk
NdhnN9LMLYIMlpnP4YDTGawr+O1kBXpyejcdAt49z9UkhFukeYGn15v6xn+np7gwTnd3sj4GNx45
mp2y7vR4tZd+hyTjxiXncw/f+uydAc7EPOdA54WPwS0kB43zISbg/kbEYU71u9/pSS03LtnL9Xjf
5RFfzyqmlZtXDvFvEe7IcnLjSm+eIaXcIsjH+B7ldtr+vl8aubkyj39zVlc8++YfX9+icOOT7VUr
cIuxl/W5udlypm8Zt4xbxi3jlnHLuGXcMm4Zt4zb5+TWEdcP/F0/HJj1tOBr+VmbP82dZwzXyq2S
UGu32KU0HKOU/cjowusjpZnZx5ZsWENiapZmP9G4j7CFjLFiIISZZW/Qs1XoDmXTXBJjKvxCJrJ2
C50v4JrrEldEnr417tYWOyLN4OZmP+f6SsMPV/IE6X/9YdfjR6RoM025tasMe+L1LpoLyAEd1RSD
mGRmCWMZm8IYGdqsJFSqj7uYdi9xRRTZGZRKuw1jX61yFHJGf6PhHKUcFWs2S0K1xpH9Rp5c4il6
LnTrfLnHFnkMeJJ3kFa5XeAsIOmaim3g06mOHCX2K7mhi8CmD2rwgKZbxG49H22pp+joZxK1lZrf
T6yv3l1dy+Vo6rrZcm59bUXXV87cMfSV9kGwO3Ekjd2Elk6V/Y11ojy8t742o2mrp9H8rrUVWVV5
GhRPVZ0OHElNPbQOq6Om1SPPf19DTbjS7bq2o+uo3RvZsjSsnmN5ots8OUf6EqB8RZp6B02olqO5
72pJqDf4zcFLiNsgqqe2RZxyrh/WJlHZXVxGVhxbp4+hOGMkG8rd7Q0Y3DvOxDCUu79lErhqfG1y
1GGMNIq+2uj1H/YQ9e9krNKF2Wujbj1/D3Efm4JkmmgOA4ZMN+/6L6vu3FSIoWuTAwx6R3y96nYt
jpodo46DqzK7RvsXjo5TkSEvwQvGqatcmzVmzVmlMm2U5ZrMruu/uX6UPvWJgY4DTzPAHoixAjey
0BQUSzfCMb6KjqF1RO9vYHX/B/0hIIoSawAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$MainForm = New-Object 'System.Windows.Forms.Form'
	$Specific_Link = New-Object 'System.Windows.Forms.LinkLabel'
	$ResetOnly_Link = New-Object 'System.Windows.Forms.LinkLabel'
	$Unlock_Link = New-Object 'System.Windows.Forms.LinkLabel'
	$Users_ListBox = New-Object 'System.Windows.Forms.ListBox'
	$Search_Txt = New-Object 'System.Windows.Forms.TextBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	<#
		Creator: Zachary C. Preston
		Date   : 7/10/2017
		Company: LRC
	#>
	
	Import-Module ActiveDirectory
	Add-Type -AssemblyName System.Windows.Forms
    $passwordResetDir = Get-ScriptDirectory
	. "$passwordResetDir\Password_Reset_Functions.ps1"
	
	############################################
	##            Event Handlers              ##
	############################################
	
	$MainForm_Load = {
		#TODO: Initialize Form Controls here
		
		$ADusers = Get-ADUser -Filter { Name -like "*" } | select -ExpandProperty Name | sort
		
		foreach ($user in $ADusers)
		{
			$Users_ListBox.Items.Add($user.toString())
		}
		
		if ($Users_ListBox.Items.Count -gt 0) { $Users_ListBox.SelectedIndex = 0 }
		$Search_Txt.Focus()
	}
	
	#region Control Helper Functions
	function Update-ListBox
	{
	<#
		.SYNOPSIS
			This functions helps you load items into a ListBox or CheckedListBox.
		
		.DESCRIPTION
			Use this function to dynamically load items into the ListBox control.
		
		.PARAMETER ListBox
			The ListBox control you want to add items to.
		
		.PARAMETER Items
			The object or objects you wish to load into the ListBox's Items collection.
		
		.PARAMETER DisplayMember
			Indicates the property to display for the items in this control.
		
		.PARAMETER Append
			Adds the item(s) to the ListBox without clearing the Items collection.
		
		.EXAMPLE
			Update-ListBox $ListBox1 "Red", "White", "Blue"
		
		.EXAMPLE
			Update-ListBox $listBox1 "Red" -Append
			Update-ListBox $listBox1 "White" -Append
			Update-ListBox $listBox1 "Blue" -Append
		
		.EXAMPLE
			Update-ListBox $listBox1 (Get-Process) "ProcessName"
		
		.NOTES
			Additional information about the function.
	#>
		
		param
		(
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			[System.Windows.Forms.ListBox]$ListBox,
			[Parameter(Mandatory = $true)]
			[ValidateNotNull()]
			$Items,
			[Parameter(Mandatory = $false)]
			[string]$DisplayMember,
			[switch]$Append
		)
		
		if (-not $Append)
		{
			$listBox.Items.Clear()
		}
		
		if ($Items -is [System.Windows.Forms.ListBox+ObjectCollection] -or $Items -is [System.Collections.ICollection])
		{
			$listBox.Items.AddRange($Items)
		}
		elseif ($Items -is [System.Collections.IEnumerable])
		{
			$listBox.BeginUpdate()
			foreach ($obj in $Items)
			{
				$listBox.Items.Add($obj)
			}
			$listBox.EndUpdate()
		}
		else
		{
			$listBox.Items.Add($Items)
		}
		
		$listBox.DisplayMember = $DisplayMember
	}
	#endregion
	
	$Search_Txt_TextChanged = {
		[string]$searchStr = $Search_Txt.Text.ToString()
		if ($searchStr.Length -ge 1)
		{
			try
			{
				$Users_ListBox.Items.Clear()
				$ADusers = Get-ADUser -LDAPFilter "(&(objectCategory=person)(objectClass=user)(name=*$searchStr*))" | select -Expand Name | Sort-Object
				foreach ($user in $ADusers)
				{
					$Users_ListBox.Items.Add($user)
					#[string]$FullName = removeLRCtext -displayName $user.toString()
					#$Users_ListBox.Items.Add($FullName)
				}
			}
			catch
			{
				
			}
		}
		else
		{
			try
			{
				$Users_ListBox.Items.Clear()
				$ADusers = Get-ADUser -LDAPFilter "(&(objectCategory=person)(objectClass=user)(name=*))" | select -Expand Name | Sort
				
				foreach ($user in $ADusers)
				{
					$Users_ListBox.Items.Add($user)
					#[string]$FullName = removeLRCtext -displayName $user.toString()
					#$Users_ListBox.Items.Add($FullName)
				}
			}
			catch
			{
				
			}
			
		}
		
		if ($Users_ListBox.Items.Count -gt 0) { $Users_ListBox.SelectedIndex = 0 }
	}
	
	$Unlock_Link_LinkClicked = [System.Windows.Forms.LinkLabelLinkClickedEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.LinkLabelLinkClickedEventArgs]
		#TODO: Place custom script here
		[string]$user = $Users_ListBox.SelectedItem.ToString()
		try
		{
			$user = toUsername -dispName $user
			Unlock-ADAccount -Identity $user
			[System.Windows.Forms.MessageBox]::Show("Account Unlocked: $user")
			writeToLog -output "$user`'s Account Unlocked"
		}
		catch
		{
			[System.Windows.Forms.MessageBox]::Show("Error: Could Not Unlock!")
			writeToLog -output "Error: $user`'s Account Could Not Be Unlocked"
		}
	}
	
	$ResetOnly_Link_LinkClicked = [System.Windows.Forms.LinkLabelLinkClickedEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.LinkLabelLinkClickedEventArgs]
		#TODO: Place custom script here
		try
		{
			[string]$user = $Users_ListBox.SelectedItem.ToString()
			$user = toUsername -dispName $user
			[string]$newPasswd = resetADPassword -username $user
			if ($newPasswd.StartsWith("1"))
			{
				$newPasswd = $newPasswd.Remove(0,1)
			}
			if ($newPasswd.Length -lt 8)
			{
				writeToLog -output "$user`'s Password Was Not Changed"
			}
			else
			{
				writeToLog -output "$user`'s Password Changed To: $newPasswd"
			}
		}
		catch
		{
			[System.Windows.Forms.MessageBox]::Show("Error: Could Not Reset!")
			writeToLog -output "Error: $user`'s Password Could Not Be Reset"
			
		}
	}
	
	$Specific_Link_LinkClicked = [System.Windows.Forms.LinkLabelLinkClickedEventHandler]{
	
		Add-Type -AssemblyName Microsoft.VisualBasic
		try
		{
			[string]$user = $Users_ListBox.SelectedItem.ToString()
			$user = toUsername -dispName $user
			$Passwd = [Microsoft.VisualBasic.Interaction]::InputBox('Enter a Password', 'New Password', "")
			Write-Host $Passwd.ToString()
			resetADPasswordSpecific -username $user -specificPass $Passwd
			writeToLog -output "$user`'s Password Changed To: $Passwd"
		}
		catch
		{
			[System.Windows.Forms.MessageBox]::Show("Error: Could Not Reset!")
			writeToLog -output "Error: $user`'s Password Could Not Be Reset"
		}
	}
	
	############################################
	##             Functions                  ##
	############################################
	
	function removeLRCtext([string]$displayName)
	{
		<#if ($displayName.Contains(" (LRC)"))
		{
			
			[string]$user =s$displayName
			#$endAt = $user.LastIndexOf('(') - 1
			#$beginIndex = $user.Length - 6
			#Write-Host $user.LastIndexOf(' ')
			#$user = $user.Substring(0, $endAt)
			$user =$user.Replace(" (LRC)", "")
			
			return $user
		}
		else
		{
			return $displayName
		}#>
		return $displayName
	}
    function Get-ScriptDirectory 
    {
       [string]$location = Split-Path -parent $PSCommandPath
       return $location
    }
	function toUsername([string]$dispName)
	{
		$User = Get-ADUser -Filter { Name -eq $dispName } | select -ExpandProperty SamAccountName
		return $User.toString()
	}
	function writeToLog([string]$output)
	{
		[string]$date = Get-Date -Format g
		[string]$filePath = "./Log.txt"
		[string]$writeOut = $date
		$writeOut += " $output"
		if (Test-Path ..\Password-Reset\log)
		{
			Write-Host "Excist"
		}
		else
		{
			mkdir ..\Password-Reset\log
		}
		
		Add-Content ..\Password-Reset\Log\log.txt "$writeOut"
		
	}	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$MainForm.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_Users_ListBox = $Users_ListBox.SelectedItems
		$script:MainForm_Search_Txt = $Search_Txt.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$Specific_Link.remove_LinkClicked($Specific_Link_LinkClicked)
			$ResetOnly_Link.remove_LinkClicked($ResetOnly_Link_LinkClicked)
			$Unlock_Link.remove_LinkClicked($Unlock_Link_LinkClicked)
			$Search_Txt.remove_TextChanged($Search_Txt_TextChanged)
			$MainForm.remove_Load($MainForm_Load)
			$MainForm.remove_Load($Form_StateCorrection_Load)
			$MainForm.remove_Closing($Form_StoreValues_Closing)
			$MainForm.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$MainForm.SuspendLayout()
	#
	# MainForm
	#
	$MainForm.Controls.Add($Specific_Link)
	$MainForm.Controls.Add($ResetOnly_Link)
	$MainForm.Controls.Add($Unlock_Link)
	$MainForm.Controls.Add($Users_ListBox)
	$MainForm.Controls.Add($Search_Txt)
	$MainForm.AutoScaleMode = 'None'
	$MainForm.AutoSize = $True
	$MainForm.AutoSizeMode = 'GrowAndShrink'
	$MainForm.ClientSize = '292, 359'
	#region Binary Data
	$MainForm.Icon = [System.Convert]::FromBase64String('
AAABAAEAQEAAAAEAIAAoQAAAFgAAACgAAABAAAAAgAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8gICD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA////
////////////////////////////////////////////////////////////////////////////
////////////+Pj4/6CgoP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/4CAgP//////////////////////////////////////////
////////////////////////////////////////////////////////////gICA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+AgID/////
////////////////////////////////////////////////////////////////////////////
//////////////////////////9gYGD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA////////////////////////////////////////////
////////////////////////////////////////////////////////////////z8/P/xAQEP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/4CAgP//////
////////////////////////////////////////////////////////////////////////////
////////////////////z8/P/xAQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/xAQEP+wsLD/////////////////////////////////v7+//xAQEP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQEP/Q0ND/////////////////////////
////////n5+f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yAg
IP/Q0ND/////////////////////////////////j4+P/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/zAwMP/w8PD/////////////////////////////////YGBg
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MDAw/xAQEP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/0BAQP/w8PD/////
///////////////////////v7+//YGBg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/QEBA//Dw8P+goKD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/2BgYP/////////////////////////////////v7+//MDAw/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/cHBw/////////////////4CAgP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3BwcP//////////////////////
///////////f39//MDAw/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/oKCg////////////////////////////UFBQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/6CgoP/////////////////////////////////Pz8//EBAQ/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8QEBD/0NDQ/////////////////////////////////8DA
wP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ/6CgoP/////////////////////////////////P
z8//EBAQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8wMDD/8PDw////
/////////////////////////////7+/v/8QEBD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ/9DQ0P//
//////////////////////////////+fn5//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP9gYGD/8PDw/////////////////////////////////4+Pj/8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/EBAQ/9DQ0P////////////////////////////////+fn5//AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+QkJD/////////////////////
/////////////////2BgYP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MDAw//Dw8P//////////////
//////////////////9gYGD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/xAQEP+wsLD/////////////////////////////////7+/v/zAwMP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/MDAw//Dw8P////////////////////////////////9gYGD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yAgIP/Q0ND/////////////////////////////////
z8/P/xAQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg////////////////////////////////
/+/v7/8wMDD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/0BAQP/w8PD/
////////////////////////////////n5+f/xAQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg
/////////////////////////////////+/v7/8wMDD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/2BgYP//////////////////////////////////////b29v/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/oKCg/////////////////////////////////8/Pz/8QEBD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/6CgoP//////////////////
///////////////v7+//UFBQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/oKCg////////////
/////////////////////8/Pz/8QEBD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/EBAQ/9DQ0P/////////////////////////////////f39//MDAw/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8QEBD/0NDQ/////////////////////////////////5+fn/8QEBD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/MDAw/+Dg4P//////////////////////////////
//+/v7//EBAQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8QEBD/0NDQ////////////////////////
/////////5+fn/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg//Dw
8P////////////////////////////////+fn5//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8w
MDD/4ODg/////////////////////////////////29vb/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/gICA//////////////////////////////////////9gYGD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8wMDD/8PDw/////////////////////////////////2Bg
YP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8QEBD/oKCg////////////////
/////////////////+/v7/8wMDD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/8PDw////
////////////////////////7+/v/0BAQP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8gICD/0NDQ/////////////////////////////////8/Pz/8gICD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP9gYGD/////////////////////////////////7+/v/zAwMP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8wMDD/8PDw////////////////////////////
/////5+fn/8QEBD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+QkJD/////////////////////
////////////z8/P/yAgIP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP9gYGD/
/////////////////////////////////////39/f/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP+goKD/////////////////////////////////z8/P/xAQEP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP+goKD/////////////////////////////////7+/v/2BgYP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQEP/AwMD/////////////////////////////////
r6+v/xAQEP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQEP/AwMD/////////////
////////////////////39/f/zAwMP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/xAQEP/Q0ND/
////////////////////////////////n5+f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/zAwMP/g4OD/////////////////////////////////z8/P/xAQEP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/xAQEP/Q0ND/////////////////////////////////f39//wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/1BQUP/w8PD/////////////////////////
////////n5+f/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg////////
////////////////////YGBg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/3Bw
cP//////////////////////////////////////YGBg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+AgID////////////v7+//UFBQ/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/EBAQ/6CgoP/////////////////////////////////v7+//QEBA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/5+f
n//v7+//MDAw/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ/9DQ0P//////////
///////////////////////Pz8//ICAg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/ICAg/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/MDAw//Dw8P////////////////////////////////+vr6//EBAQ/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/YGBg////////////////////////////
//////////+Pj4//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
kJCQ////////////////////////////////////////////////////////////////////////
//////////////////////////////+AgID/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8QEBD/wMDA////////////////////////////////////////
////////////////////////////////////////////////////////////////////gICA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/wMDA////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////4CAgP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/2BgYP//////////////////////////////////////////////
//////////////////////////////////////////////////////////////////+AgID/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/gICA////
////////////////////////////////////////////////////////////////////////////
////////////////////////////gICA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP+vr6//7+/v/0BAQP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/EBAQ
/zAwMP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/')
	#endregion
	$MainForm.MaximumSize = '308, 398'
	$MainForm.MinimumSize = '308, 398'
	$MainForm.Name = 'MainForm'
	$MainForm.StartPosition = 'CenterScreen'
	$MainForm.Text = 'Password Reset'
	$MainForm.add_Load($MainForm_Load)
	#
	# Specific_Link
	#
	$Specific_Link.Font = 'Microsoft Sans Serif, 12pt'
	$Specific_Link.Location = '199, 322'
	$Specific_Link.Name = 'Specific_Link'
	$Specific_Link.Size = '77, 23'
	$Specific_Link.TabIndex = 4
	$Specific_Link.TabStop = $True
	$Specific_Link.Text = 'Specific'
	$Specific_Link.TextAlign = 'MiddleCenter'
	$Specific_Link.add_LinkClicked($Specific_Link_LinkClicked)
	#
	# ResetOnly_Link
	#
	$ResetOnly_Link.Font = 'Microsoft Sans Serif, 12pt'
	$ResetOnly_Link.Location = '100, 322'
	$ResetOnly_Link.Name = 'ResetOnly_Link'
	$ResetOnly_Link.Size = '87, 23'
	$ResetOnly_Link.TabIndex = 3
	$ResetOnly_Link.TabStop = $True
	$ResetOnly_Link.Text = 'Reset Only'
	$ResetOnly_Link.TextAlign = 'MiddleCenter'
	$ResetOnly_Link.add_LinkClicked($ResetOnly_Link_LinkClicked)
	#
	# Unlock_Link
	#
	$Unlock_Link.Font = 'Microsoft Sans Serif, 12pt'
	$Unlock_Link.Location = '7, 322'
	$Unlock_Link.Name = 'Unlock_Link'
	$Unlock_Link.Size = '78, 23'
	$Unlock_Link.TabIndex = 2
	$Unlock_Link.TabStop = $True
	$Unlock_Link.Text = 'Unlock'
	$Unlock_Link.TextAlign = 'MiddleCenter'
	$Unlock_Link.add_LinkClicked($Unlock_Link_LinkClicked)
	#
	# Users_ListBox
	#
	$Users_ListBox.Font = 'Microsoft Sans Serif, 12pt'
	$Users_ListBox.FormattingEnabled = $True
	$Users_ListBox.ItemHeight = 20
	$Users_ListBox.Location = '12, 45'
	$Users_ListBox.Name = 'Users_ListBox'
	$Users_ListBox.Size = '268, 264'
	$Users_ListBox.TabIndex = 1
	#
	# Search_Txt
	#
	$Search_Txt.Font = 'Microsoft Sans Serif, 12pt'
	$Search_Txt.Location = '12, 9'
	$Search_Txt.Name = 'Search_Txt'
	$Search_Txt.Size = '268, 26'
	$Search_Txt.TabIndex = 0
	$Search_Txt.add_TextChanged($Search_Txt_TextChanged)
	$MainForm.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $MainForm.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$MainForm.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$MainForm.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$MainForm.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $MainForm.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: Password_Reset.ps1
	<#
		Creator: Zachary C. Preston
		Date   : 7/10/2017
		Company: LRC
	#>
	
	function isLegislator([string]$user)
	{
		$fullName = Get-ADUser -Identity $user | select -expand Name
		if ($fullName.Contains("(State"))
		{
			Write-Host "true"
			return $true
		}
		else
		{
			return $false
		}
	}
	function generateNewPassword([string]$user)
	{
		
		$userToReset = $user
		
		$newPass = $userToReset[$userToReset.IndexOf('_') + 1]
		$newPass = $newPass + $userToReset[0]
		$newPass = $newPass.ToLower()
		$dayOfWeek = (Get-Date).DayOfWeek.value__
		switch ($dayOfWeek)
		{
			1
			{
				$newPass += "!";
				break
			}
			2
			{
				$newPass += "@";
				break
			}
			3
			{
				$newPass += "#";
				break
			}
			4
			{
				$newPass += "`$";
				break
			}
			5
			{
				$newPass += "%";
				break
			}
			default
			{
				$newPass += "!";
				break
			}
		}
		if (isLegislator -user $user)
		{
			$UserOU = "legi"
		}
		else
		{
			[string]$distinguishedName = Get-ADUser -Identity $user | select -expand DistinguishedName
			[string[]]$OUs = $distinguishedName.Split("=")
			$UserOU = $OUs[3].Substring(0, $OUs[3].IndexOf(","))
			if ($UserOU.Length -le 3)
			{
				$UserOU = $UserOU.Substring(0, 3) + "1"
			}
			else
			{
				$UserOU = $UserOU.Substring(0, 4)
			}
			if ($UserOU.Equals("STAT") -or $UserOU.Equals("Stat"))
			{
				$UserOU = "sgov"
			}
			$UserOU = $UserOU.ToLower()
		}
		$newPass += $UserOU
		#$minute = 3
		$minute = (Get-Date).Minute
		if ($minute -le 9)
		{
			$newPass += "0" + $minute
		}
		else
		{
			$newPass += $minute
		}
		return $newPass
	}
	function resetADPassword ([string]$username)
	{
		Add-Type -AssemblyName System.Windows.Forms
		Add-Type -AssemblyName System.Drawing
		Add-Type -AssemblyName PresentationFramework
		
		[string]$newPassword = generateNewPassword -user $username
		$securePass = ConvertTo-SecureString -String $newPassword -AsPlainText -Force
		$displayName = Get-ADUser $username | select -expand Name
		#$confirmYesNo = [System.Windows.MessageBox]::Show("Reset Password To $newPassword" + "?", "Password Reset For $displayName", 'YesNo', 'Error')
		$confirmBox = New-Object -ComObject Wscript.Shell
		$answer = $confirmBox.popup("Reset " + $username + "'s password to: " + $newPassword + "?", 0, "Reset User Password: " + $username, 4)
		if ($answer -eq 6)
		{
			$secondAnswer = $confirmBox.popup("Commit Changes to $($displayName)?", 0, $displayName + "'s new password: " + $newPassword, 4)
			if ($secondAnswer -eq 6)
			{
				try
				{
					Set-ADAccountPassword $username -NewPassword $securePass -Reset
					unlockAccount -username $username
					$clipboardBiulder = "The Password For The Account: "
					$clipboardBiulder += "$displayName has been reset to: `r`n`t"
					$clipboardBiulder += "$newPassword `r`nThis can be changed after two days.`r`nThank You"
					Set-Clipboard -Value $clipboardBiulder
					$confirmBox.popup("Changes Complete, Results Copied To Clipboard!", 0, "Applied!")
					#$outputBox.AppendText("The password for the account: ")
					return $newPassword
					
				}
				catch
				{
					$confirmBox.popup("Error: Could Not Perform Action!")
				}
			}
			else
			{
				$confirmBox.popup("No Changes Made")
			}
		}
		else
		{
			$confirmBox.popup("No Changes Made")
		}
		
	}
	function resetADPasswordSpecific ([string]$username, [string]$specificPass)
	{
		Add-Type -AssemblyName System.Windows.Forms
		Add-Type -AssemblyName System.Drawing
		Add-Type -AssemblyName PresentationFramework
		
		$newPassword = $specificPass
		$securePass = ConvertTo-SecureString -String $newPassword -AsPlainText -Force
		$displayName = Get-ADUser $username | select -expand Name
		$confirmYesNo = [System.Windows.MessageBox]::Show("Reset Password To $newPassword" + "?", "Password Reset For $displayName", 'YesNo', 'Error')
		$confirmBox = New-Object -ComObject Wscript.Shell
		$answer = $confirmBox.popup("Reset " + $username + "'s password to: " + $newPassword + "?", 0, "Reset User Password: " + $username, 4)
		if ($answer -eq 6)
		{
			$secondAnswer = $confirmBox.popup("Commit Changes to $($displayName)?", 0, $displayName + "'s new password: " + $newPassword, 4)
			if ($secondAnswer -eq 6)
			{
				try
				{
					Set-ADAccountPassword $username -NewPassword $securePass -Reset
					unlockAccount -username $username
					$clipboardBiulder = "The Password For The Account: "
					$clipboardBiulder += "$displayName has been reset to: `r`n`t"
					$clipboardBiulder += "$newPassword `r`nThis can be changed after two days.`r`nThank You"
					Set-Clipboard -Value $clipboardBiulder
					$confirmBox.popup("Changes Complete, Results Copied To Clipboard!", 0, "Applied!")
					#$outputBox.AppendText("The password for the account: ")
					
					Write-Host "$displayName $newPassword"
				}
				catch
				{
					$confirmBox.popup("Error: Could Not Perform Action!")
				}
			}
			else
			{
				$confirmBox.popup("No Changes Made")
			}
		}
		else
		{
			$confirmBox.popup("No Changes Made")
		}
		
	}
	function unlockAccount([string]$username)
	{
		Unlock-ADAccount -Identity $username
	}
	
#endregion Source: Password_Reset.ps1

#Start the application
Main ($CommandLine)
